name: Close Pull Requests

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "Please file pull requests in the [main project repository](https://github.com/stdlib-js/stdlib)."